### ISSUE TITLE
Certain replays throwing errors

### ISSUE THREAD

**Issue by gabcinder2004** [HydraOrc/w3g#1]
Hi, not sure if you are still maintaining this project, but wanted to post an issue that I'm seeing.

1v1 with observers
https://www.wcreplays.com/replay.php?m=View&rid=99489

FFA
https://www.wcreplays.com/replay.php?m=View&rid=105744

Both of these replays (along with more examples) are having issues parsing. The 1v1 cannot parse the loser_team or winner_team, while the FFA fails to even successfully parse at all. Are you able to take a look? Thanks!

**Comment by HydraOrc** [comment]
Hello, please provide another links to the replays, since they are not working at the moment, and i will take a look.
Thank you for the feedback.
