### ISSUE TITLE
sprintf is not defined

### ISSUE THREAD

**Issue by chknlittle** [HydraOrc/w3g#2]
Hi!

Was really happy to find this repo but could not get it to work. Getting the following error:

ReferenceError: sprintf is not defined at w3g_julas.js:413

Forked the repo and and poked around to see if I could replace or import sprintf somehow but I'm afraid that I'm not familiar with coffeescript to even understand where the entry point of the application is.

Any chance you can help me solve the issue?

Thanks!

**Comment by HydraOrc** [comment]
I am sorry for the inconvinience, as all the sprintf calls should be written as php.sprintf
Fixed now in the version 1.0.4
